spring:
  profiles:
    active:
      - dev
---
server:
  port: 1005
  servlet:
    context-path: /

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db_springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 595251308
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
    appname: student-provider
    instance-id: student-provider:1005
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:2004/eureka

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
  name: zs
  tel: 110
---
server:
  port: 1005
  servlet:
    context-path: /

spring:
  profiles: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db_springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root
    password: 595251308
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost
    appname: student-provider
    instance-id: student-provider:1004
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:2004/eureka

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
  name: zs
  tel: 110
